baseURL = "https://rachitkakkar.com/"
languageCode = "en-us"
title = "Rachit Kakkar"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    hl_inline = false
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = "dracula"
    tabWidth = 4

[menu]
    [[menu.nav]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

    [[menu.nav]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2

    [[menu.nav]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 3